# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-25 04:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exploit',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='ExploitType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('etype', models.CharField(max_length=10)),
                ('description', models.CharField(max_length=140)),
            ],
        ),
        migrations.CreateModel(
            name='Name',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=40)),
                ('nickname', models.CharField(max_length=25)),
            ],
        ),
        migrations.CreateModel(
            name='Vuln',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.BigIntegerField()),
                ('description', models.CharField(max_length=140)),
                ('vuln', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScoreboardEKO13.Name')),
            ],
        ),
        migrations.AddField(
            model_name='exploit',
            name='etype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ScoreboardEKO13.ExploitType'),
        ),
        migrations.AddField(
            model_name='exploit',
            name='exploit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ScoreboardEKO13.Name'),
        ),
        migrations.AddField(
            model_name='exploit',
            name='vuln',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='ScoreboardEKO13.Vuln'),
        ),
    ]
